name: Docker Compose CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Mise à jour vers actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2 # Mise à jour vers docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0 # Utilisation de docker/build-push-action@v2.7.0
        with:
          context: .
          file: docker-compose.yml
          push: true
