name: Build ,Test & Deploy to Azure App Service

on:
  push:
    branches:
      - master

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Set up environment
        run: |
          export NODE_ENV=test
      - name: 'npm install, build, and test'
        run: |
          npm install
          npm run build --if-present
          npm run test:e2e --if-present
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: nest-starter-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
